server:
  port: 8761
   
   
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server: 
        enable-SelfPreservation: true
    
spring:
   main:
     allow-bean-definition-overriding: true
