server:
  port: 7070
   
spring: 
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:mem:testdb
   application:
     name: USER-SERVICE
   zipkin:
    base-url: http://127.0.0.1:9411/
spring.jpa:
  database: H2
  hibernate.ddl-auto: update
  show-sql: true